page作成
WakayamaUnivTeamDev-SeiyaMaruyama/sengex2023A pull request #5
Opened 2023-06-29 06:51 UTC by yyy0848

2023-06-29 07:14 UTC, eve00 requested changes
修正頼みます！

2023-06-29 07:14 UTC, eve00 commented on SubjectList.html
> +        <a href="file:///C:/Users/Owner/Documents/%E6%8E%88%E6%A5%AD%E8%B3%87%E6%96%99/%E3%82%BD%E3%83%95%E3%83%88%E3%82%A6%E3%82%A7%E3%82%A2%E3%82%A8%E3%83%B3%E3%82%B8%E3%83%8B%E3%82%A2%E3%83%AA%E3%
```suggestion
        <a href="./ShowReview.html">インターネット技術</a>


```

2023-06-29 07:14 UTC, eve00 commented on ShowReview.html
> +      <input type="button" value="編集" onclick="location.href='file:///C:/Users/Owner/Documents/%E6%8E%88%E6%A5%AD%E8%B3%87%E6%96%99/%E3%82%BD%E3%83%95%E3%83%88%E3%82%A6%E3%82%A7%E3%82%A2%E3%82%A8%E3%
ここのhrefも！

2023-06-29 07:14 UTC, eve00 commented on EditReview.html
> +      <input type="button" value="保存" onclick="location.href='file:///C:/Users/Owner/Documents/%E6%8E%88%E6%A5%AD%E8%B3%87%E6%96%99/%E3%82%BD%E3%83%95%E3%83%88%E3%82%A6%E3%82%A7%E3%82%A2%E3%82%A8%E3%
ここのhrefも！

2023-06-29 11:14 UTC, yyy0848 commented on SubjectList.html
> +        <a href="file:///C:/Users/Owner/Documents/%E6%8E%88%E6%A5%AD%E8%B3%87%E6%96%99/%E3%82%BD%E3%83%95%E3%83%88%E3%82%A6%E3%82%A7%E3%82%A2%E3%82%A8%E3%83%B3%E3%82%B8%E3%83%8B%E3%82%A2%E3%83%AA%E3%
修正しました！

2023-06-29 11:14 UTC, yyy0848 commented on ShowReview.html
> +      <input type="button" value="編集" onclick="location.href='file:///C:/Users/Owner/Documents/%E6%8E%88%E6%A5%AD%E8%B3%87%E6%96%99/%E3%82%BD%E3%83%95%E3%83%88%E3%82%A6%E3%82%A7%E3%82%A2%E3%82%A8%E3%
修正しました！

2023-06-29 11:14 UTC, yyy0848 commented on EditReview.html
> +      <input type="button" value="保存" onclick="location.href='file:///C:/Users/Owner/Documents/%E6%8E%88%E6%A5%AD%E8%B3%87%E6%96%99/%E3%82%BD%E3%83%95%E3%83%88%E3%82%A6%E3%82%A7%E3%82%A2%E3%82%A8%E3%
修正しました！

2023-07-03 00:13 UTC, SeiyaMaruyama approved these changes
LGTM

2023-07-03 00:16 UTC, merged